<style>
    .current_time{
        text-align: center;
    }
    .subButton{
        border: 1px solid #DDD;
        background-color: #F2F2F2;
        color: black;
        text-transform: uppercase;
        text-decoration: none;
        padding: 4px;
    }
    .contact{
        font-weight: bold;
    }
    .email{
        text-decoration: underline;
        color: blue;
    }
    .contact_info{
        width: 830px;
        margin: 0 auto;
        height: auto;
        clear: both;
        overflow: hidden;
    }
    .Container2{
        float: left;
        width: 320px;
        font-size: 14px;
        height: auto;
        overflow: hidden;
    }
    .labels{
        margin-left: 90px;
        padding-left: 20px;
    }
    .h2header{
        border: 1px solid #DDD;
        background-color: #F2F2F2;
        font-size: 28;
        text-align: center;
        padding: 5px;
    }
    .basic_information{
        clear: both;
        padding-bottom: 10px;
    }
    div#container p{
        padding: 5px;
        margin-left: 5px;
        border: 1px solid #DDD;
        height: 54px;
    }
    .autogenerated{
        padding-top: 50px;
        text-align: center;
        clear: both;
        margin: 0 auto;
        width: 533px;
        height: auto;
        overflow: hidden;
        font-weight: bold;
    }
    .profileContainer{
        position: relative;
        top: 10px;
        font-family: Times New Roman;
        border: 1px solid #ddd;
        margin: 0 auto; 
        width: 850px;
        height: auto;
        overflow: hidden; 
        clear: both;
    }
</style>
<style>
    table.punishmentTable{
        width: 800px;
        border: none;
        font-family: times new roman;
    }
    tbody{
        border: 1px solid #ddd;
    }
    table.punishmentTable th{
        padding: 0px;
        text-align: center;
        text-decoration: none;
        padding-bottom: 0px;
        border: 1px solid #ddd;
    }
    table.punishmentTable td{
        text-align: center;
        border: 1px solid #ddd;
        padding: 0px;
    }
    img.backButtonImage{
        overflow: hidden;
        height: auto;
        top: 10;
        position: relative;
        width: 31;
    }
    img.editButtonImage{
        overflow: hidden;
        height: auto;
        top: 5;
        position: relative;
        width: 25;
    }
    img.deleteButtonImage{
        overflow: hidden;
        height: auto;
        top: 7;
        position: relative;
        width: 25.3;
    }
    img.printButtonImage{
        overflow: hidden;
        height: auto;
        top: 7;
        position: relative;
        width: 24;
    }

</style>
<?php get_header(); ?>
<script type="text/javascript">
    $(document).ready(function(){
        $('#deleteButtonId').click(function(){
            var std_id = $( this ).attr("student_ID");
            var url = "./index.php?p=delete_student&std_id="+std_id;
            $.msgBox({
                title: "Delete "+std_id+" permanently",
                content: "Information will be permanently deleted. Are you sure?",
                type: "confirm",
                buttons: [{ value: "Ok" },{value: 'Cancel'}],
                success: function (result) {
                    if(result == 'Ok'){
                        $.ajax({
                            type: "POST",
                            url: url,
                            data: $("#approval_form").serialize(), // serializes the form's elements.
                            success: function(data)
                            {
                                $.msgBox({
                                    title: "Information",
                                    content: data,
                                    type: "info",
                                    buttons: [{ value: "Ok" }],
                                    success: function (result) {
                                        window.location.href="./index.php?p=office_user_panel_com_butex_sis_017734";       
                                    }
                                });
                                
                                // show response from the php script.
                            },
                            error: function(){
                                $.msgBox({
                                    title: "Error",
                                    content: "Got an Error",
                                    type: "error",
                                    buttons: [{ value: "Ok" }],
                                    success: function (result) {
                                                        
                                    }
                                });
                            }
                        });
                    }
                }
            });   
        })
    })
</script>
<div id="container">
    <?php if (!logged_in()) : ?>
        <p style="color: red;">First You Need To Log In Properly..    <a href="./index.php?p=login" title="Login">Login</a></p>
    <?php else : ?>
        <div class="logOutButton">
            <a class="logoutLink"<a href="./index.php?p=logout">Logout</a>
        </div>
        <?php $m = $_GET['std']; ?>
        <form id="approval_form" class='formApp' method='POST' action='' enctype='multipart/form-data'>
            <input type='hidden' name='std_id'  value='<?php echo $m; ?>'/>
        </form>
      <!--    <P>After that you will be able to login with the user id <strong><?php reg_info('student_id'); ?></strong>.</p>-->
           <a class="subButton" href="./index.php?p=office_user_panel_com_butex_sis_017734#tabs-1">Back TO Admin <img class="backButtonImage" src="template/images/back.png"/></a>
           <a class="subButton" target="_blank" href="./index.php?p=profilePdf&std_id=<?php echo $m; ?>">Print <img class="printButtonImage" src="template/images/print.jpg"/></a>
        <?php if (isSuperAdmin()) : ?>
            <a class="subButton" href="./index.php?p=update_form&std=<?php echo $m; ?>">Edit Profile <img class="editButtonImage" src="template/images/edit.png"/></a>
            <a class="subButton" href="./index.php?p=manual_result_entry&std_id=<?php echo $m; ?>">Result Entry</a>
            <a class="subButton" href="./index.php?p=norm_entry&std_id=<?php echo $m; ?>">punishment record</a>
            <a class="subButton deleteClass" id="deleteButtonId" href="#" student_ID="<?php echo $m; ?>">Delete Profile <img class="deleteButtonImage" src="template/images/delete.jpg"/></a>
        <?php endif; ?>
            
        <?php

        function getStudentStatus($rowData) {
            if (!empty($rowData)) {
                if ($rowData == 'enrolled') {
                    echo 'Enrolled';
                }
                if ($rowData == 'passed_out') {
                    echo 'Passed Out';
                }
                if ($rowData == 'admission_canceled') {
                    echo 'Admission Canceled';
                }
            } else {
                echo '';
            }
        }

        $sql = "SELECT * FROM input WHERE std_id=$m";
        $result = mysql_query($sql);
        while ($row = mysql_fetch_array($result)) {
            $student_name = $row['stud_name'];
            $al_dept = $row['al_dept'];
            $mi_dept = $row['mi_dept'];
            $s_ship = $row['s_ship'];
            $session = $row['session'];
            $admission_roll = $row['admission_test_roll_no'];
            $merit_position = $row['merit_position'];
            $dept = $row['dept'];
            $father_name = $row['father_name'];
            $mother_name = $row['mother_name'];
            $dob = $row['dob'];
            $gender = $row['gender'];
            $p_address = $row['p_address'];
            $c_address = $row['c_address'];
            $std_contact_no = $row['stud_contact_no'];
            $gard_contact_no = $row['grd_contact_no'];
            $nationality = $row['nationality'];
            $emr_contact_no = $row['emergency_contact_no'];
            $emr_contact_address = $row['emergency_contact_address'];
            $blood_grp = $row['blood_grp'];
            $ssc_board = $row['ssc_board'];
            $ssc_roll = $row['ssc_roll'];
            $ssc_gpa = $row['ssc_gpa'];
            $ssc_ac = $row['ssc_academic_institute'];
            $ssc_year = $row['ssc_year'];
            $hsc_board = $row['hsc_board'];
            $hsc_ac = $row['hsc_academic_institute'];
            $hsc_year = $row['hsc_year'];
            $hsc_roll = $row['hsc_roll'];
            $hsc_gpa = $row['hsc_gpa'];
            $grd_income = $row['grd_income'];
            $extra_curricular = $row['extra_curricular'];
            $link = $row['link'];
            $religion = $row['religion'];
            $student_status = $row['student_status'];
            if ($link == 'no') {
                $link = 'No_Image.jpg';
            }
            $reg_no = $row['reg_no'];
            $over_rec = $row['over_rec'];

            function chooseProgram($m) {
                $BSC = "B.Sc in Textile Engineering";
                $MSC = "M.Sc in Textile Engineering";
                if ($m[4] == '1') {
                    echo "B.Sc in Textile Engineering";
                }
                if ($m[4] == '2') {
                    echo "M.Sc in Textile Engineering";
                }
            }

        }
        ?>
        <style>
            div.label{
                width: 30%;
                float: left;
                overflow: hidden;
            }
            div.dataField{
                width: 100%;
                overflow: hidden;
                height: 40px;
                clear: both;
            }
            div.Infovalue{
                width: 60%;
                float: left;
                padding-left: 10%;
                overflow: hidden;
            }
            div.contact_info{
                font-size: 15px
            }
            div.contact_info h2{
                font-size: 15px;
            }
            span.colon{
                float: right;
            }
            span.std{
                font-weight: bold;
            }
            h1.sectionHeader{
                text-align: center;
                text-transform: uppercase;
                margin-bottom: 30px;
                font-family: arial, sans-serif, times new roamn; 
                font-size: 20px;
            }
            div.profileContainer{
                font-family: arial, sans-serif, times new roamn; 
            }


        </style>
        <div class="profileContainer" style=" ">
            <h1 class="sectionHeader" style="">Student Profile</h1>
            <div class="contact_info">
                <div class="basic" style="float: left; width: 650px;">
                    <div class="dataField">
                        <div class="label">
                            <span class="stdIdLabel std">
                                Student ID<span class="colon">:</span>
                            </span>
                        </div>
                        <div class="Infovalue">
                            <span class="stdIdvalue std">
                                <?php echo $m; ?>
                            </span>
                        </div>
                    </div>
                    <div class="dataField">
                        <div class="label">
                            <span class="stdNameLabel std">
                                Student Name<span class="colon">:</span>
                            </span>
                        </div>
                        <div class="Infovalue">
                            <span class="stdNamevalue std">
                                <?php echo $student_name; ?>
                            </span>
                        </div>
                    </div>
                    <div class="dataField">
                        <div class="label">
                            Registration No.<span class="colon">:</span>
                        </div>
                        <div class="Infovalue">
                            <?php echo $reg_no; ?>
                        </div>
                    </div>
                    <div class="dataField">
                        <div class="label">
                            Department<span class="colon">:</span>
                        </div>
                        <div class="Infovalue">
                            <?php echo $dept; ?>
                        </div>
                    </div>

                    <div class="dataField">
                        <div class="label">
                            Course/Program Title<span class="colon">:</span>
                        </div>
                        <div class="Infovalue">
                            <?php chooseProgram($m); ?>
                        </div>
                    </div>

                    <div class="dataField">
                        <div class="label">
                            Session<span class="colon">:</span>
                        </div>
                        <div class="Infovalue">
                            <?php echo $session; ?>
                        </div>
                    </div>
                    <div class="dataField">
                        <div class="label">
                            Studnet Contact No<span class="colon">:</span>
                        </div>
                        <div class="Infovalue"> 
                            +88<?php echo $std_contact_no; ?> 
                        </div>
                    </div>
                    <div class="dataField">
                        <div class="label">
                            Current Address<span class="colon">:</span>
                        </div>
                        <div class="Infovalue">
                            <?php echo $c_address; ?>
                        </div>
                    </div>
                </div>
                <div class="basic imageContainer" style="float: right">
                    <img width="170" src="./template/uploaded_student_images/<?php echo $link; ?>" />
                </div>
            </div>
            <div class="basic_information" style="width: 800; margin: 0 auto; font-size: 15px;">
                <h1 class="sectionHeader" style="text-transform: none;">Basic Information</h1>
                <div class="dataField">
                    <div class="label">
                        Father's Name<span class="colon">:</span>
                    </div>
                    <div class="Infovalue"> 
                        <?php echo $father_name; ?> 
                    </div>
                </div>
                <div class="dataField">
                    <div class="label">
                        Mother's Name<span class="colon">:</span>
                    </div>
                    <div class="Infovalue"> 
                        <?php echo $mother_name; ?> 
                    </div>
                </div>
                <div class="dataField">
                    <div class="label">
                        Date of Birth<span class="colon">:</span>
                    </div>
                    <div class="Infovalue"> 
                        <?php echo $dob; ?> 
                    </div>
                </div>
                <div class="dataField">
                    <div class="label">
                        Permanent Address<span class="colon">:</span>
                    </div>
                    <div class="Infovalue"> 
                        <?php echo $p_address; ?> 
                    </div>
                </div>
                <div class="dataField">
                    <div class="label">
                        Nationality<span class="colon">:</span>
                    </div>
                    <div class="Infovalue"> 
                        <?php echo $nationality; ?> 
                    </div>
                </div>
                <div class="dataField">
                    <div class="label">
                        Gender<span class="colon">:</span>
                    </div>
                    <div class="Infovalue"> 
                        <?php echo $gender; ?> 
                    </div>
                </div>
                <div class="dataField">
                    <div class="label">
                        Blood Group<span class="colon">:</span>
                    </div>
                    <div class="Infovalue"> 
                        <?php echo $blood_grp; ?> 
                    </div>
                </div>
                <div class="dataField">
                    <div class="label">
                        Religion<span class="colon">:</span>
                    </div>
                    <div class="Infovalue"> 
                        <?php echo $religion; ?> 
                    </div>
                </div>
            </div>
            <div class="basic_information" style="width: 800; margin: 0 auto; font-size: 15px;">
                <h1 class="sectionHeader" style="text-transform: none;">Emergency Information</h1>

                <div class="dataField">
                    <div class="label">
                        Guardian Contanct No.<span class="colon">:</span>
                    </div>
                    <div class="Infovalue"> 
                        <?php echo $gard_contact_no; ?> 
                    </div>
                </div>
                <div class="dataField">
                    <div class="label">
                        Emergency Contact No.<span class="colon">:</span>
                    </div>
                    <div class="Infovalue"> 
                        <?php echo $emr_contact_no; ?> 
                    </div>
                </div>
                <div class="dataField">
                    <div class="label">
                        Emergency Contact Address.<span class="colon">:</span>
                    </div>
                    <div class="Infovalue"> 
                        <?php echo $emr_contact_address; ?> 
                    </div>
                </div>
            </div>
            <div class="basic_information" style="width: 800; margin: 0 auto; font-size: 15px;">
                <h1 class="sectionHeader" style="text-transform: none;">Admission Information</h1>
                <div class="dataField">
                    <div class="label">
                        Admission Roll No.<span class="colon">:</span>
                    </div>
                    <div class="Infovalue"> 
                        <?php echo $admission_roll; ?> 
                    </div>
                </div>
                <div class="dataField">
                    <div class="label">
                        Merit Position.<span class="colon">:</span>
                    </div>
                    <div class="Infovalue"> 
                        <?php echo $merit_position; ?> 
                    </div>
                </div>
                <div class="dataField">
                    <div class="label">
                        Alloted Department<span class="colon">:</span>
                    </div>
                    <div class="Infovalue"> 
                        <?php echo $al_dept; ?> 
                    </div>
                </div>
                <div class="dataField">
                    <div class="label">
                        Migrated Department<span class="colon">:</span>
                    </div>
                    <div class="Infovalue"> 
                        <?php echo $mi_dept; ?> 
                    </div>
                </div>
            </div>
            <style>
                .academic_info{
                    border-collapse: collapse;
                    border: 1px solid black;
                    width: 95%;
                    margin: 0 auto;
                }
                .academic_info th{
                    border: 1px solid black;
                    height: 25px;
                    background-color: #ddd;
                    color: black;
                    font-weight: bold;
                }
                .academic_info td{
                    border: 1px solid black;
                    text-align: center;
                    padding: 4px;
                    height: 22px
                }
            </style>


            <div class="basic_information" style="width: 840; margin: 0 auto; font-size: 15px;">
                <h1 class="sectionHeader" style="text-transform: none;">Academic Information</h1>
                <table class="academic_info" style="">
                    <tbody>
                        <tr>
                            <th>Examination</th>
                            <th>Institution</th>
                            <th>Board</th>
                            <th>Exam. Year</th>
                            <th>Exam. Roll</th>
                            <th>GPA</th>
                        </tr>
                        <tr>
                            <td>Secondary School Certificate(SSC)</td>
                            <td><?php echo $ssc_ac ?></td>
                            <td><?php echo $ssc_board ?></td>
                            <td><?php echo $ssc_year ?></td>
                            <td><?php echo $ssc_roll ?></td>
                            <td><?php echo $ssc_gpa ?></td>
                        </tr>
                        <tr>
                            <td>Higher Secondary Certificate(HSC)</td>
                            <td><?php echo $hsc_ac ?></td>
                            <td><?php echo $hsc_board ?></td>
                            <td><?php echo $hsc_year ?></td>
                            <td><?php echo $hsc_roll ?></td>
                            <td><?php echo $hsc_gpa ?></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="basic_information" style="width: 840; margin: 0 auto; font-size: 15px;">
                <h1 class="sectionHeader" style="text-transform: none;">Results</h1>
                <table class='academic_info' style='margin: 0 auto;'>
                    <th>Level,Term</th>
                    <th>Exam Year</th>
                    <th>Term/Subject GPA</th>
                    <th>CGPA</th>
                    <th>Fail/Retake Subject(s)</th>
                    <th>Remarks</th>
                    <?php

                    function getLevelTerm($lt) {
                        $level = $lt[1];
                        $term = $lt[3];
                        $levelTermText = 'Level-' . $level . ',Term-' . $term . '';
                        return $levelTermText;
                    }

                    $sql = "SELECT * FROM result_status WHERE student_id=$m ORDER BY entry_date_time ASC";
                    $result = mysql_query($sql);
                    if (!empty($result)) {
                        $i = 0;
                        while ($row = mysql_fetch_array($result)) {
                            echo '<tr>
                                <td>' . getLevelTerm($row['level_term']) . '</td>
                                <td>' . $row['exam_year'] . '</td>
                                <td>' . $row['gpa'] . '</td>
                                <td>' . $row['cgpa'] . '</td>
                                <td>' . $row['backlog_subject'] . '</td>
                                <td>' . $row['remarks'] . '</td>
                            </tr>';
                            $i++;
                        }
                    }
                    ?>
                </table>
            </div>
            <?php
//        $sql = "SELECT * FROM norm WHERE std_id=$m";
//        $result = mysql_query($sql);
//        $num_row = mysql_num_rows($result);
//        if ($num_row >= 1) {
//            while ($row = mysql_fetch_array($result)) {
//                echo "<tr>";
//                echo "<td class='table_data'>" . $row['date_time'] . "</td>";
//                echo "<td class='table_data'>" . $row['std_id'] . "</td>";
//                echo "<td class='table_data'>" . $row['punishment'] . "</td>";
//                echo "<td class='table_data'>" . $row['warning'] . "</td>";
//                echo "</tr>";
//            }
//            echo "</table>";
//            echo '</div>';
//        }
//        
            ?>
            
            <!--  Punishment -->
            <div class="basic_information" style="width: 840; margin: 0 auto; font-size: 15px;">
                <h1 class="sectionHeader" style="text-transform: none;">Punishment Record</h1>
                <table class='academic_info' style='margin: 0 auto;'>
                    <th>Date/Time</th>
                    <th>Warning</th>
                    <th>Punishment</th>
                    <?php
                    $sql = "SELECT * FROM norm WHERE std_id=$m ORDER BY date_time ASC";
                    $result = mysql_query($sql);
                    if (!empty($result)) {
                        $i = 0;
                        while ($row = mysql_fetch_array($result)) {
                            echo '<tr>
                                <td>' . $row['date_time'] . '</td>
                                <td>' . $row['warning'] . '</td>
                                <td>' . $row['punishment'] . '</td>
                            </tr>';
                            $i++;
                        }
                    }
                    ?>
                </table>
            </div>
            
            
            <div class="basic_information" style="width: 800; margin: 0 auto; font-size: 15px;">
                <h1 class="sectionHeader" style="text-transform: none;">Other Information</h1>
                <div class="dataField">
                    <div class="label">
                        Guardian Income<span class="colon">:</span>
                    </div>
                    <div class="Infovalue"> 
                        <?php echo $grd_income; ?> 
                    </div>
                </div>
                <div class="dataField">
                    <div class="label">
                        Extra-Curricular Activity<span class="colon">:</span>
                    </div>
                    <div class="Infovalue"> 
                        <?php echo $extra_curricular; ?> 
                    </div>
                </div>
<!--                <div class="dataField">
                    <div class="label">
                        Punishment<span class="colon">:</span>
                    </div>
                    <div class="Infovalue"> 
                        <?php //echo ""; ?> 
                    </div>
                </div>
                <div class="dataField">
                    <div class="label">
                        Warning<span class="colon">:</span>
                    </div>
                    <div class="Infovalue"> 
                        <?php // echo ""; ?> 
                    </div>
                </div>-->
                <div class="dataField">
                    <div class="label">
                        OverAll Record<span class="colon">:</span>
                    </div>
                    <div class="Infovalue"> 
                        <?php echo $over_rec; ?> 
                    </div>
                </div>
                <div class="dataField">
                    <div class="label">
                        Student Status<span class="colon">:</span>
                    </div>
                    <div class="Infovalue"> 
                        <?php echo getStudentStatus($student_status); ?> 
                    </div>
                </div>

            </div>
        </div>
        <div class="basic_information">
            <div class="autogenerated">
                <div style="font-size: 11px;">Report Generated By BUTex Student Information System<div>
                        <div style="font-family: CopperPlate Gothic bold;">Bangladesh University of Textiles</div>
                    </div>
                </div>
            </div>
        <?php endif; ?>
    </div>
    <!-- END Content -->
    <?php get_footer(); ?>
