<style>
  .current_time{
    text-align: center;
  }
  .subButton{
    border: 1px solid #DDD;
    background-color: #F2F2F2;
    color: black;
    text-transform: uppercase;
    text-decoration: none;
    padding: 4px;
  }
  .contact{
    font-weight: bold;
  }
  .email{
    text-decoration: underline;
    color: blue;
  }
  .contact_info{
    width: 830px;
    margin: 0 auto;
    height: auto;
    clear: both;
    overflow: hidden;
  }
  .Container2{
    float: left;
    width: 320px;
    font-size: 14px;
    height: auto;
    overflow: hidden;
  }
  .labels{
    margin-left: 90px;
    padding-left: 20px;
  }
  .h2header{
    border: 1px solid #DDD;
    background-color: #F2F2F2;
    font-size: 28;
    text-align: center;
    padding: 5px;
  }
  .basic_information{
    clear: both;
    padding-bottom: 10px;
  }
  div#container p{
    padding: 5px;
    margin-left: 5px;
    border: 1px solid #DDD;
    height: 41px;
  }
  .autogenerated{
    text-align: center;
    clear: both;
    margin: 0 auto;
    width: 400px;
    height: auto;
    overflow: hidden;
  }
  .profileContainer{
    position: relative;
    top: 10px;
    font-family: Times New Roman;
    border: 1px solid #ddd;
    margin: 0 auto; 
    width: 850px;
    height: auto;
    overflow: hidden; 
    clear: both;
  }
</style>
<style>
  table.punishmentTable{
    width: 800px;
    border: none;
    font-family: times new roman;
  }
  tbody{
    border: 1px solid #ddd;
  }
  table.punishmentTable th{
    padding: 0px;
    text-align: center;
    text-decoration: none;
    padding-bottom: 0px;
    border: 1px solid #ddd;
  }
  table.punishmentTable td{
    text-align: center;
    border: 1px solid #ddd;
    padding: 0px;
  }
</style>
<?php get_header(); ?>
<div id="container">
  <?php if (!logged_in()) : ?>
    <p style="color: red;">First You Need To Log In Properly..    <a href="./index.php?p=login" title="Login">Login</a></p>
  <?php else : ?>
    <div class="logOutButton">
      <a class="logoutLink"<a href="./index.php?p=logout">Logout</a>
    </div>
  <!--    <P>After that you will be able to login with the user id <strong><?php reg_info('student_id'); ?></strong>.</p>-->
    <a class="subButton" href="./index.php?p=office_user_panel_com_butex_sis_017734#tabs-2">Back TO Admin</a>
    <?php
    $m = $_GET['std'];
    $sql = "SELECT * FROM input WHERE std_id=$m";
    $result = mysql_query($sql);
    while ($row = mysql_fetch_array($result)) {
      $student_name = $row['stud_name'];
      $admission_roll = $row['admission_test_roll_no'];
      $merit_position = $row['merit_position'];
      $dept = $row['dept'];
      $father_name = $row['father_name'];
      $mother_name = $row['mother_name'];
      $dob = $row['dob'];
      $p_address = $row['p_address'];
      $c_address = $row['c_address'];
      $std_contact_no = $row['stud_contact_no'];
      $gard_contact_no = $row['grd_contact_no'];
      $nationality = $row['nationality'];
      $emr_contact_no = $row['emergency_contact_no	'];
      $emr_contact_address = $row['emergency_contact_address'];
      $blood_grp = $row['blood_grp'];
      $ssc_board = $row['ssc_board'];
      $ssc_roll = $row['ssc_roll'];
      $ss_gpa = $row['ssc_gpa'];
      $ssc_ac = $row['ssc_academic_institute'];
      $ssc_year = $row['ssc_year'];
      $hsc_board = $row['hsc_board'];
      $hsc_ac = $row['hsc_academic_institute'];
      $hsc_year = $row['hsc_year'];
      $hsc_roll = $row['hsc_roll'];
      $hsc_gpa = $row['hsc_gpa'];
      $grd_income = $row['grd_income'];
      $extra_curricular = $row['extra_curricular'];
      $link = $row['link'];
    }
    ?>
    <div class="profileContainer" style=" ">
      <h1 style="text-align: center; text-transform: uppercase;">Student Profile</h1>
      <div class="contact_info">
        <div class="basic" style="float: left; width: 400px;">
          <div class="contact"><h2><?php echo $student_name; ?></h2></div>
          <div class="contact">Contact: +88<?php echo $std_contact_no; ?> </div>
          <div class="contact email">Address :<?php echo $c_address; ?></div>
        </div>
        <div class="basic imageContainer" style="float: right">
          <img width="170" src="./template/uploaded_student_images/<?php echo $link; ?>" />
        </div>
      </div>
      <div class="basic_information">
        <h2 class="h2header">Basic Information</h2>
        <div class="labels Container2">
          <p>Name:</p>
          <p>Father's Name:</p>
          <p>Mother's Name:</p>
          <p>Date of Birth:</p>
          <p>Current Address:</p>
          <p>Permanent Address:</p>
          <p>Blood Group:</p>
          <p>Nationality:</p>
        </div>
        <div class="Container2">
          <p><?php echo $student_name; ?></p>
          <p><?php echo $father_name; ?></p>
          <p><?php echo $mother_name; ?></p>
          <p><?php echo $dob; ?></p>
          <p><?php echo $c_address; ?></p>
          <p><?php echo $p_address; ?></p>
          <p><?php echo $blood_grp; ?></p>
          <p><?php echo $nationality; ?></p>
        </div>
      </div>
      <div class="basic_information">
        <h2 class="h2header">Academic Information</h2>
        <div style="clear:both;">
          <h3 class="h3header">Secondary School Certificate</h3>
          <div class="labels Container2">
            <p>SSC Board:</p>
            <p>Institution:</p>
            <p>SSC Year:</p>
            <p>SSC GPA:</p>
            <p>SSC Roll:</p>
          </div>
          <div class="Container2">
            <p><?php echo $ssc_board; ?></p>
            <p><?php echo $ssc_ac; ?></p>
            <p><?php echo $ssc_year; ?></p>
            <p><?php echo $ss_gpa; ?></p>
            <p><?php echo $ssc_roll; ?></p>
          </div>
        </div>
        <div style="clear:both;">
          <h3 class="h3header">Higher Secondary Certificate:</h3>
          <div class="labels Container2">
            <p>HSC Board:</p>
            <p>Institution:</p>
            <p>HSC Year:</p>
            <p>HSC GPA:</p>
            <p>HSC Roll:</p>
          </div>
          <div class="Container2">
            <p><?php echo $hsc_board; ?></p>
            <p><?php echo $hsc_ac; ?></p>
            <p><?php echo $hsc_year; ?></p>
            <p><?php echo $hsc_gpa; ?></p>
            <p><?php echo $hsc_roll; ?></p>
          </div>
        </div>
      </div>
      <div class="basic_information">
        <h2 class="h2header">Department</h2>
        <div class="labels Container2">
          <p>Department:</p>
          <p>Student ID:</p>
          <p>Admission Test Roll:</p>
          <p>Merit Position:</p>
        </div>
        <div class="Container2">
          <p><?php echo $dept; ?></p>
          <p><?php echo $m; ?></p>
          <p><?php echo $admission_roll; ?></p>
          <p><?php echo $merit_position; ?></p>
        </div>
      </div>
      <?php
      $sql = "SELECT * FROM exam WHERE std_id=$m";
      $result = mysql_query($sql);
      while ($row_exam = mysql_fetch_array($result)) {
        $std_id = $row_exam['std_id'];
        $l1t1 = $row_exam['L1T1GPA'];
        $l1t2 = $row_exam['L1T2GPA'];
        $l2t1 = $row_exam['L2T1GPA'];
        $l2t2 = $row_exam['L2T2GPA'];
        $l3t1 = $row_exam['L3T1GPA'];
        $l3t2 = $row_exam['L3T2GPA'];
        $l4t1 = $row_exam['L4T1GPA'];
        $l4t2 = $row_exam['L4T2GPA'];
        $cgpa = $row_exam['CGPA'];
        $record = $row_exam['RECORD'];
        $note = $row_exam['note'];
      }
      ?>
      <div class="basic_information">
        <h2 class="h2header">Results</h2>
        <div class="labels Container2">
          <p>Department:</p>
          <p>Student ID:</p>
          <p>GPA Level1 Term1:</p>
          <p>GPA Level1 Term2:</p>
          <p>GPA Level2 Term1:</p>
          <p>GPA Level2 Term2:</p>
          <p>GPA Level3 Term1:</p>
          <p>GPA Level3 Term2:</p>
          <p>GPA Level4 Term1:</p>
          <p>GPA Level4 Term2:</p>
          <p>CGPA:</p>
          <p>Record:</p>
          <p>Note:</P>
        </div>
        <div class="Container2">
          <p><?php echo $dept; ?></p>
          <p><?php echo $std_id; ?></p>
          <p><?php echo $l1t1; ?></p>
          <p><?php echo $l1t2; ?></p>
          <p><?php echo $l2t1; ?></p>
          <p><?php echo $l2t2; ?></p>
          <p><?php echo $l3t1; ?></p>
          <p><?php echo $l3t2; ?></p>
          <p><?php echo $l4t1; ?></p>
          <p><?php echo $l4t2; ?></p>
          <p><?php echo $cgpa; ?></p>
          <p><?php echo $record; ?></p>
          <p><?php echo $note; ?></p>
        </div>
      </div>


      <?php
      $sql = "SELECT * FROM norm WHERE std_id=$m";
      $result = mysql_query($sql);
      $num_row = mysql_num_rows($result);
      if ($num_row >= 1) {
        echo '<div class="basic_information">
        <h2 class="h2header">Record Of Punishment</h2>';
        echo "<table class='punishmentTable' style='margin: 0 auto;' border='1px solid black' cellpadding=4 cellspacing=5>
          <tr>
            <th class='table_header'>Date Time</th>
            <th class='table_header'>Student ID</th>
            <th class='table_header'>Punishment</th>
            <th class='table_header'>Warning</th>
          </tr>";

        while ($row = mysql_fetch_array($result)) {
          echo "<tr>";
          echo "<td class='table_data'>" . $row['date_time'] . "</td>";
          echo "<td class='table_data'>" . $row['std_id'] . "</td>";
          echo "<td class='table_data'>" . $row['punishment'] . "</td>";
          echo "<td class='table_data'>" . $row['warning'] . "</td>";
          echo "</tr>";
        }
        echo "</table>";
        echo '</div>';
      }
      ?>
    
    <div class="basic_information">
      <h2 class="h2header"></h2>
      <div class="autogenerated">
        <h3>Report Generated By BUTEX Information System</h3>
        <p>Bangladesh University of Textiles</p>
      </div>
    </div>
  </div>
<?php endif; ?>
</div>
<!-- END Content -->
<?php get_footer(); ?>